/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.16
 * Generated at: 2019-08-08 01:02:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/C:/Users/user1/Desktop/git/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Outflearn/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Users/user1/Desktop/git/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Outflearn/WEB-INF/lib/spring-webmvc-5.1.8.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1560401236000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-5.1.3.RELEASE.jar", Long.valueOf(1564460692261L));
    _jspx_dependants.put("jar:file:/C:/Users/user1/Desktop/git/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Outflearn/WEB-INF/lib/spring-security-taglibs-5.1.3.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1547128166000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1563149540840L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.1.8.RELEASE.jar", Long.valueOf(1563149466333L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fcsrfMetaTags_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsec_005fcsrfMetaTags_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsec_005fcsrfMetaTags_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"\">\r\n");
      out.write("  ");
      if (_jspx_meth_sec_005fcsrfMetaTags_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  <title>Outflearn</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap -->\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/bootstrap.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"resources/fonts/font-awesome/css/font-awesome.css\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Stylesheet\r\n");
      out.write("    ================================================== -->\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/style.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/nivo-lightbox/nivo-lightbox.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/nivo-lightbox/default.css\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Lato:400,700\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Raleway:300,400,500,600,700,800,900\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- reference your copy Font Awesome here (from our Kits or by hosting yourself) -->\r\n");
      out.write("  <script src=\"https://kit.fontawesome.com/27cb20e940.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function () {\r\n");
      out.write("\t\tvar token = $(\"meta[name='_csrf']\").attr(\"content\");\r\n");
      out.write("\t\tvar header = $(\"meta[name='_csrf_header']\").attr(\"content\");\r\n");
      out.write("\t\t$(document).ajaxSend(function(e, xhr, options) {\r\n");
      out.write("\t\t\txhr.setRequestHeader(header, token);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"//developers.kakao.com/sdk/js/kakao.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body id=\"page-top\" data-spy=\"scroll\" data-target=\".navbar-fixed-top\">\r\n");
      out.write("  <!-- ==========================================Navigation==========================================-->\r\n");
      out.write("  <nav id=\"menu\" class=\"navbar navbar-default navbar-fixed-top\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("      <div class=\"navbar-header\">\r\n");
      out.write("        <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\"\r\n");
      out.write("          data-target=\"#bs-example-navbar-collapse-1\"> <span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("            class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> </button>\r\n");
      out.write("        <a class=\"navbar-brand page-scroll\" href=\"#page-top\" style=\"color: #6372ff\">Outflearn</a> </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("        <ul class=\"nav navbar-nav navbar-center\">\r\n");
      out.write("          <li><a href=\"LectureList.html\">강좌 둘러보기</a></li>\r\n");
      out.write("          <li><a href=\"void:0\">로드맵 학습</a></li>\r\n");
      out.write("          <li><a href=\"void:0\">아웃프런 소개</a></li>\r\n");
      out.write("          <li><a href=\"void:0\">라이브</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("          <li class=\"dropdown\"><a href=\"void:0\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"><i class=\"far fa-user\"\r\n");
      out.write("                style=\"color: #6372ff \"></i>\r\n");
      out.write("              <div class=\"dropdown-menu\" role=\"menu\" aria-expanded=\"navbarDropdown\">\r\n");
      out.write("                <a href=\"void:0\">로그아웃</a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </a></li>\r\n");
      out.write("          <li><a href=\"/Outflearn/loginfrom\">로그인</a></li>\r\n");
      out.write("          <li><a href=\"/Outflearn/registerform.do\">회원가입</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("  <!-- Header -->\r\n");
      out.write("  <header id=\"header\">\r\n");
      out.write("    <div class=\"intro\">\r\n");
      out.write("      <div class=\"overlay\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-8 col-md-offset-2 intro-text\">\r\n");
      out.write("            \r\n");
      out.write("            <!-- 로그인 폼 영역 시작  -->\r\n");
      out.write("            <script type=\"text/javascript\">\r\n");
      out.write("            \r\n");
      out.write("            $(\"#submit\").submit(function(){\r\n");
      out.write("            \tif($(\"#id\").val()==\"\"){\r\n");
      out.write("            \t\talert(\"아이디를 입력해주세요\");\r\n");
      out.write("            \t}else if($(\"#passwd\").val()==\"\"){\r\n");
      out.write("            \t\talert(\"비밀번호를 입력해 주세요\");\r\n");
      out.write("            \t}\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            </script>\r\n");
      out.write("            \r\n");
      out.write("              <form action=\"/Outflearn/login\" method=\"post\" id=\"test\">\r\n");
      out.write("                <input type=\"hidden\" name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                <input type=\"text\" name=\"loginId\" id=\"loginId\" placeholder=\"ID\">\r\n");
      out.write("                <input type=\"password\" name=\"loginPw\" id=\"loginPw\" placeholder=\"PASSWORD\">\r\n");
      out.write("                <input type=\"submit\" value=\"Sign in\" id=\"submit\"><br/><br/>\r\n");
      out.write("\t\t\t\t<label for=\"remember-me\" style=\"padding-left: 60%;\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" id=\"remember-me\" name=\"remember-me\">\r\n");
      out.write("\t\t\t\tRmember Me\r\n");
      out.write("\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t<br/><br/>\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("              </form>\r\n");
      out.write("              <br />\r\n");
      out.write("\r\n");
      out.write("              <a href=\"/Outflearn/findIdForm.do\">아이디 찾기</a>\r\n");
      out.write("              <a href=\"/Outflearn/findPwForm.do\" style=\"padding-left: 2%;\">비밀번호를 잊으셨나요?</a><br/><br/>\r\n");
      out.write("              \r\n");
      out.write("              <a id=\"kakao-login-btn\"></a>\r\n");
      out.write("\t\t\t  <a href=\"http://developers.kakao.com/logout\"></a>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<script type='text/javascript'>\r\n");
      out.write("\t\t\t\t  //<![CDATA[\r\n");
      out.write("\t\t\t\t    // 사용할 앱의 JavaScript 키를 설정해 주세요.\r\n");
      out.write("              \t    Kakao.init('85e61dfa4e850de4478ab8c6df1a737a');\r\n");
      out.write("\t\t\t\t    // 카카오 로그인 버튼을 생성합니다.\r\n");
      out.write("\t\t\t\t    Kakao.Auth.createLoginButton({\r\n");
      out.write("\t\t\t\t      container: '#kakao-login-btn',\r\n");
      out.write("\t\t\t\t      success: function(authObj) {\r\n");
      out.write("\t \t\t\t\t        alert(JSON.stringify(authObj));\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t    \t  Kakao.API.request({\r\n");
      out.write("\t\t\t\t    \t\t url: '/v1/user/me',\r\n");
      out.write("\t\t\t\t    \t\t success: function(res){\r\n");
      out.write("\t\t\t\t    \t\t\t \r\n");
      out.write("\t\t\t\t    \t\t\t alert(res);\t\t\t\t    \t\t\t \r\n");
      out.write("\t\t\t\t    \t\t\t res.id += \"@k\";\t\r\n");
      out.write("\t\t\t\t    \t\t\talert(res.id);\r\n");
      out.write("\t\t\t\t    \t\t\t\r\n");
      out.write("\t\t\t\t    \t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t    \t\t\t\turl: \"idChk.do\",  //id체크\r\n");
      out.write("\t\t\t\t    \t\t\t\tdata: \"id=\"+res.id,\r\n");
      out.write("\t\t\t\t    \t\t\t\t\r\n");
      out.write("\t\t\t\t    \t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t    \t\t\t\t\talert(data.idChk);\r\n");
      out.write("\t\t\t\t    \t\t\t\t\tif(data.idChk==true){ //아이디가 없다면 회원가입 \r\n");
      out.write("\t\t\t\t    \t\t\t\t\t\talert(\"회원가입\");\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t\tvar param = \r\n");
      out.write("\t\t\t\t    \t\t\t\t\t\t{\"user_id\":res.id, \"user_pw\":res.id, \"user_email\":res.id, \"user_nickname\":res.id }\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t\t\turl: \"kakaoUserinsert\",\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t\t\tmethod: \"POST\",\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t\t\tdata: param\t,\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t\t\tsuccess : function(){ //회원가입 성공, 가입 후 로그인ㄱㄱ\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t\t\t\talert(\"회원가입 완료\");\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t\t\t\t$(\"form\").attr(\"method\",\"post\").attr(\"action\",\"/Outflearn/login?id=\"+res.id+\"&passwd=\"+res.id).submit();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t}else{ //아이디가 있다면 로그인 (시큐리티 로그인ㄱㄱ)\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t\talert(\"로그인하러 갑니다~!\");\r\n");
      out.write("\t\t    \t\t\t\t\t\t\t\t$(\"form\").attr(\"method\",\"post\").attr(\"action\",\"/Outflearn/login?id=\"+res.id+\"&passwd=\"+res.id).submit();\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t}\r\n");
      out.write("\t\t\t\t    \t\t\t\t}\r\n");
      out.write("\t\t\t\t    \t\t\t});\r\n");
      out.write("\t\t\t\t    \t\t },\r\n");
      out.write("\t\t\t\t    \t\t fail: function(error){\r\n");
      out.write("\t\t\t\t    \t\t\t alert(JSON.stringify(err));\r\n");
      out.write("\t\t\t\t    \t\t }\r\n");
      out.write("\t\t\t\t    \t  });\r\n");
      out.write("\t\t\t\t      },\r\n");
      out.write("\t\t\t\t      fail: function(err) {\r\n");
      out.write("\t\t\t\t         alert(JSON.stringify(err));\r\n");
      out.write("\t\t\t\t      }\r\n");
      out.write("\t\t\t\t    });\r\n");
      out.write("\t\t\t\t  //]]>\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\r\n");
      out.write("              \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<br/><br/>\t\r\n");
      out.write("            <a href=\"void:0\"><img alt=\"\"\r\n");
      out.write("                  src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/loginIMG/naverLogin.png\"></a>\r\n");
      out.write("\t\t\t<a href=\"\">깃허브 로그인</a>\r\n");
      out.write("              <!-- 로그인 폼 끝 -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Contact Section -->\r\n");
      out.write("  <div id=\"contact\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"col-md-8\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"section-title\">\r\n");
      out.write("            <h2>Get In Touch</h2>\r\n");
      out.write("            <p>Please fill out the form below to send us an email and we will get back to you as soon as possible.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <form name=\"sentMessage\" id=\"contactForm\" novalidate>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-6\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <input type=\"text\" id=\"name\" class=\"form-control\" placeholder=\"Name\" required=\"required\">\r\n");
      out.write("                  <p class=\"help-block text-danger\"></p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-6\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <input type=\"email\" id=\"email\" class=\"form-control\" placeholder=\"Email\" required=\"required\">\r\n");
      out.write("                  <p class=\"help-block text-danger\"></p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <textarea name=\"message\" id=\"message\" class=\"form-control\" rows=\"4\" placeholder=\"Message\"\r\n");
      out.write("                required></textarea>\r\n");
      out.write("              <p class=\"help-block text-danger\"></p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"success\"></div>\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-custom btn-lg\">Send Message</button>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-md-3 col-md-offset-1 contact-info\">\r\n");
      out.write("        <div class=\"contact-item\">\r\n");
      out.write("          <h3>Contact Info</h3>\r\n");
      out.write("          <p><span><i class=\"fa fa-map-marker\"></i> Address</span>4321 California St,<br>\r\n");
      out.write("            San Francisco, CA 12345</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"contact-item\">\r\n");
      out.write("          <p><span><i class=\"fa fa-phone\"></i> Phone</span> +1 123 456 1234</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"contact-item\">\r\n");
      out.write("          <p><span><i class=\"fa fa-envelope-o\"></i> Email</span> info@company.com</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-md-12\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"social\">\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><a href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("              <li><a href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("              <li><a href=\"#\"><i class=\"fa fa-google-plus\"></i></a></li>\r\n");
      out.write("              <li><a href=\"#\"><i class=\"fa fa-youtube\"></i></a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- Footer Section -->\r\n");
      out.write("  <div id=\"footer\">\r\n");
      out.write("    <div class=\"container text-center\">\r\n");
      out.write("      <p>Shared by <i class=\"fa fa-love\"></i><a href=\"https://bootstrapthemes.co\">BootstrapThemes</a></p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"resources/js/template/jquery.1.11.1.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"resources/js/template/bootstrap.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"resources/js/template/nivo-lightbox.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"resources/js/template/jqBootstrapValidation.js\"></script>\r\n");
      out.write("  <!-- script type=\"text/javascript\" src=\"resources/js/template/contact_me.js\"></script> -->\r\n");
      out.write("  <script type=\"text/javascript\" src=\"resources/js/template/main.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"resources/js/utils/login.js?ver=1\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_sec_005fcsrfMetaTags_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:csrfMetaTags
    org.springframework.security.taglibs.csrf.CsrfMetaTagsTag _jspx_th_sec_005fcsrfMetaTags_005f0 = (org.springframework.security.taglibs.csrf.CsrfMetaTagsTag) _005fjspx_005ftagPool_005fsec_005fcsrfMetaTags_005fnobody.get(org.springframework.security.taglibs.csrf.CsrfMetaTagsTag.class);
    boolean _jspx_th_sec_005fcsrfMetaTags_005f0_reused = false;
    try {
      _jspx_th_sec_005fcsrfMetaTags_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fcsrfMetaTags_005f0.setParent(null);
      int _jspx_eval_sec_005fcsrfMetaTags_005f0 = _jspx_th_sec_005fcsrfMetaTags_005f0.doStartTag();
      if (_jspx_th_sec_005fcsrfMetaTags_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fcsrfMetaTags_005fnobody.reuse(_jspx_th_sec_005fcsrfMetaTags_005f0);
      _jspx_th_sec_005fcsrfMetaTags_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fcsrfMetaTags_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fcsrfMetaTags_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/login.jsp(112,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty ERRORMSG }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t<p>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ERRORMSG }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\t</p>\t\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
