/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.16
 * Generated at: 2019-08-19 02:13:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.Auth;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/user1/Desktop/git/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/Outflearn/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1563149540840L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("\n");
      out.write("  <title>Outflearn</title>\n");
      out.write("\n");
      out.write("<!-- loginform css -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/loginForm.css\">\n");
      out.write("\n");
      out.write("<!-- 카카오 네이버 -->\n");
      out.write("<script src=\"//developers.kakao.com/sdk/js/kakao.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"https://static.nid.naver.com/js/naveridlogin_js_sdk_2.0.0.js\" charset=\"utf-8\"></script>\n");
      out.write("\n");
      out.write("<!-- 제이쿼리 -->\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\n");
      out.write(" \n");
      out.write("</head>\n");
      out.write("<body >\n");
      out.write("\t\n");
      out.write("\t<!-- Header  -->\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../header/MainHeader.jsp", out, false);
      out.write("\n");
      out.write("\t<!-- Header  -->\n");
      out.write("\t\n");
      out.write("\t  <header id=\"header\">\n");
      out.write("\t    <div class=\"intro\">\n");
      out.write("\t      <div class=\"overlay\">\n");
      out.write("\t        <div class=\"container\">\n");
      out.write("\t          <div class=\"row\">\n");
      out.write("\t            <div class=\"col-md-8 col-md-offset-2 intro-text\">\n");
      out.write("\t            <div class=\"login-form\">\n");
      out.write("\t            <!-- 로그인 폼 영역 시작  -->\n");
      out.write("\t            <div class=\"modal-header\">\n");
      out.write("\t\t        <a id=\"login-logo\" style=\"text-align: center;\" >Outflearn</a> \n");
      out.write("\t        \t</div>\n");
      out.write("\t            <div class=\"modal-body\">\n");
      out.write("\t            <br/><br/>\n");
      out.write("\t\t\t\t\n");
      out.write("\t              <form action=\"/Outflearn/login\" method=\"post\" id=\"loginform\" name=\"loginform\">\n");
      out.write("\t                <input type=\"hidden\" name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("\t                <input type=\"text\" name=\"loginId\" id=\"loginId\" placeholder=\"  아이디 입력\" ><br/>\n");
      out.write("\t                <input type=\"password\" name=\"loginPw\" id=\"loginPw\" placeholder=\"  비밀번호 입력\" style=\"margin-top: 2%;\"><br/><br/>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t                <input type=\"submit\" value=\"Sign in\" id=\"submitBTN\" >\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" id=\"remember-me\" name=\"remember-me\" style=\"margin-left: 2%;\">\n");
      out.write("\t\t\t\t\t<span>Rmember Me</span>\n");
      out.write("\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<br/><br/>\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t              </form>\n");
      out.write("\t\t\t\t<br/>\n");
      out.write("\t              <a href=\"/Outflearn/findIdForm.do\">아이디 찾기</a>\n");
      out.write("\t              <a href=\"/Outflearn/findPwForm.do\" style=\"padding-left: 2%;\">비밀번호를 잊으셨나요?</a><br/><br/>\n");
      out.write("\t              \n");
      out.write("\t              <!-- 카카오 로그인 시작 -->\n");
      out.write("\t              <a id=\"kakao-login-btn\"></a>\n");
      out.write("\t\t\t\t  <a href=\"http://developers.kakao.com/logout\"></a>\n");
      out.write("\t\t\t\t  <!-- 카카오로그인.js -->\n");
      out.write("\t\t\t\t  <script type=\"text/javascript\" src=\"resources/js/utils/kakaologin.js\"></script><br/><br/>\t\n");
      out.write("\t\t\t\t  <!-- 카카오 로그인 끝 -->\n");
      out.write("\t\t\t\t  <!-- ============================================= -->\n");
      out.write("\t              <!-- 네이버 로그인  시작-->  \n");
      out.write("\t              <!-- callback.jsp와 함께 사용  -->   \n");
      out.write("\t\t\t      <div id=\"naverIdLogin\"></div>\n");
      out.write("\t\t\t\t  <script type=\"text/javascript\">\n");
      out.write("\t\t\t\t\tvar naverLogin = new naver.LoginWithNaverId(\n");
      out.write("\t\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\t\tclientId: \"xsVfuuGnIVuwdJhzN_0M\",\n");
      out.write("\t\t\t\t\t\t\tcallbackUrl: \"http://localhost:8787/Outflearn/naverCallback\",\n");
      out.write("\t\t\t\t\t\t\tisPopup: false, /* 팝업을 통한 연동처리 여부 */\n");
      out.write("\t\t\t\t\t\t\tloginButton: {color: \"green\", type: 3, height: 48} /* 로그인 버튼의 타입을 지정 */\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t);\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t/* 설정정보를 초기화하고 연동을 준비 */\n");
      out.write("\t\t\t\t\tnaverLogin.init();\n");
      out.write("\t\t\t\t</script>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\n");
      out.write("              \n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<br/><br/>\t\n");
      out.write("            <a href=\"void:0\"><img alt=\"\"\n");
      out.write("                  src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/loginIMG/naverLogin.png\"></a>\n");
      out.write("\t\t\t<a href=\"\">깃허브 로그인</a>\n");
      out.write("              <!-- 로그인 폼 끝 -->\n");
      out.write("\t\t\t\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </header>\n");
      out.write("\n");
      out.write("\n");
      out.write("  <!-- Contact Section -->\n");
      out.write("  <div id=\"contact\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <div class=\"col-md-8\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"section-title\">\n");
      out.write("            <h2>Get In Touch</h2>\n");
      out.write("            <p>Please fill out the form below to send us an email and we will get back to you as soon as possible.</p>\n");
      out.write("          </div>\n");
      out.write("          <form name=\"sentMessage\" id=\"contactForm\" novalidate>\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-md-6\">\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                  <input type=\"text\" id=\"name\" class=\"form-control\" placeholder=\"Name\" required=\"required\">\n");
      out.write("                  <p class=\"help-block text-danger\"></p>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-md-6\">\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                  <input type=\"email\" id=\"email\" class=\"form-control\" placeholder=\"Email\" required=\"required\">\n");
      out.write("                  <p class=\"help-block text-danger\"></p>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <textarea name=\"message\" id=\"message\" class=\"form-control\" rows=\"4\" placeholder=\"Message\"\n");
      out.write("                required></textarea>\n");
      out.write("              <p class=\"help-block text-danger\"></p>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"success\"></div>\n");
      out.write("            <button type=\"submit\" class=\"btn btn-custom btn-lg\">Send Message</button>\n");
      out.write("          </form>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"col-md-3 col-md-offset-1 contact-info\">\n");
      out.write("        <div class=\"contact-item\">\n");
      out.write("          <h3>Contact Info</h3>\n");
      out.write("          <p><span><i class=\"fa fa-map-marker\"></i> Address</span>4321 California St,<br>\n");
      out.write("            San Francisco, CA 12345</p>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"contact-item\">\n");
      out.write("          <p><span><i class=\"fa fa-phone\"></i> Phone</span> +1 123 456 1234</p>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"contact-item\">\n");
      out.write("          <p><span><i class=\"fa fa-envelope-o\"></i> Email</span> info@company.com</p>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"col-md-12\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"social\">\n");
      out.write("            <ul>\n");
      out.write("              <li><a href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>\n");
      out.write("              <li><a href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>\n");
      out.write("              <li><a href=\"#\"><i class=\"fa fa-google-plus\"></i></a></li>\n");
      out.write("              <li><a href=\"#\"><i class=\"fa fa-youtube\"></i></a></li>\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  <!-- Footer Section -->\n");
      out.write("  <div id=\"footer\">\n");
      out.write("    <div class=\"container text-center\">\n");
      out.write("      <p>Shared by <i class=\"fa fa-love\"></i><a href=\"https://bootstrapthemes.co\">BootstrapThemes</a></p>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  <script type=\"text/javascript\" src=\"resources/js/template/jquery.1.11.1.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"resources/js/template/bootstrap.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"resources/js/template/nivo-lightbox.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"resources/js/template/jqBootstrapValidation.js\"></script>\n");
      out.write("  <!-- script type=\"text/javascript\" src=\"resources/js/template/contact_me.js\"></script> -->\n");
      out.write("  <script type=\"text/javascript\" src=\"resources/js/template/main.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"resources/js/utils/login.js?ver=1\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/Auth/login.jsp(56,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty ERRORMSG }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\t\t\t\t\n");
          out.write("\t\t\t\t\t<span id=\"errorMSG\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ERRORMSG }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\t\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
