DROP TABLE BASKET;

CREATE TABLE BASKET(
USER_NUM NUMBER REFERENCES USER_INFO(USER_NUM) NOT NULL ON DELETE CASCADE,
CLASS_NUM NUMBER REFERENCES CLASS_INFO(CLASS_NUM) NOT NULL ON DELETE CASCADE
);


INSERT INTO BASKET VALUES(62, 3)
SELECT * FROM BASKET;

INSERT INTO BASKET VALUES(1, 4);
INSERT INTO BASKET VALUES(1, 5);
INSERT INTO BASKET VALUES(1, 3);

SELECT * FROM BASKET WHERE USER_NUM = 61;
DELETE  FROM BASKET


-- 결제 완료시 장바구니 삭제
DELETE FROM BASKET WHERE USER_NUM = 61;
		DELETE FROM BASKET WHERE USER_NUM = #{user_num }
