DROP TABLE BASKET;

CREATE TABLE BASKET(
USER_NUM NUMBER REFERENCES USER_INFO(USER_NUM) NOT NULL,
CLASS_NUM NUMBER REFERENCES CLASS_INFO(CLASS_NUM) NOT NULL
);

select * from user_info;
select * from class_info;

SELECT * FROM BASKET;

INSERT INTO BASKET VALUES(2, 2);

INSERT INTO BASKET VALUES(41, 3)

INSERT INTO BASKET VALUES(41, 2)

SELECT USER_NUM FROM CLASS_INFO WHERE USER_NUM = 61;

INSERT INTO BASKET VALUES(61, 3)
