------------------------------------------ 강좌 내용 - > DB추가
DROP TABLE CLASS_INTRODUCE;

CREATE TABLE CLASS_INTRODUCE(
CLASS_NUM NUMBER REFERENCES CLASS_INFO(CLASS_NUM) ON DELETE CASCADE NOT NULL,
CLASS_CONTENT CLOB NOT NULL
)

SELECT CLASS_CONTENT FROM CLASS_INTRODUCE WHERE CLASS_NUM = 1;

INSERT INTO CLASS_INTRODUCE VALUES(1, '가나다라마바사아자차카타파하')

UPDATE  CLASS_INTRODUCE SET CLASS_CONTENT = '강선웅' WHERE CLASS_NUM = 1;
SELECT CLASS_CONTENT FROM CLASS_INTRODUCE WHERE CLASS_NUM = #{class_num }