DROP TABLE CLASS_CATEGORY;

CREATE TABLE CLASS_CATEGORY(

CLASS_NUM NUMBER NOT NULL,
MAIN_NUM NUMBER NOT NULL,
SUB_NUM NUMBER NOT NULL

);

SELECT * FROM CLASS_CATEGORY;

INSERT INTO CLASS_CATEGORY VALUES (1,1,1);
INSERT INTO CLASS_CATEGORY VALUES (2,1,2);
INSERT INTO CLASS_CATEGORY VALUES (3,1,1);
INSERT INTO CLASS_CATEGORY VALUES (4,2,10);
INSERT INTO CLASS_CATEGORY VALUES (5,3,15);

SELECT CLASS_NUM FROM CLASS_CATEGORY WHERE SUB_NUM=1;
