------------------------------------------ 강좌 내용 - > DB추가
DROP TABLE CLASS_INTRODUCE;

CREATE TABLE CLASS_INTRODUCE(
CLASS_NUM NUMBER REFERENCES CLASS_INFO(CLASS_NUM) ON DELETE CASCADE NOT NULL,
CLASS_CONTENT CLOB NOT NULL
)

SELECT * FROM CLASS_INTRODUCE;

INSERT INTO CLASS_INTRODUCE VALUES(1, '가나다라마바사아자차카타파하')
