------------------------------------------ 강좌후기
DROP TABLE CLASS_REVIEW
--글 번호 시퀀스(일반적인 번호)
DROP SEQUENCE BOARD_NO_SQ;
--그룹번호 시퀀스(답글이 달렸을 때 )
DROP SEQUENCE QA_GROUPNO_SQ;

--글 번호 시퀀스(일반적인 번호)
CREATE SEQUENCE BOARD_NO_SQ;

--그룹번호 시퀀스(답글이 달렸을 때 )
CREATE SEQUENCE QA_GROUPNO_SQ;


CREATE TABLE CLASS_REVIEW(
CLASS_NUM NUMBER REFERENCES CLASS_INFO(CLASS_NUM) ON DELETE CASCADE NOT NULL,
BOARD_NO NUMBER PRIMARY KEY,
QA_GROUPNO NUMBER NOT NULL,
QA_GROUPSQ NUMBER NOT NULL,
QA_TITLETAB NUMBER NOT NULL,
USER_NUM NUMBER REFERENCES USER_INFO(USER_NUM) ON DELETE CASCADE NOT NULL,
REVIEW_CONTENT VARCHAR2(4000) NOT NULL,
USER_STAR NUMBER NOT NULL,
USER_NICKNAME VARCHAR2(1000) NOT NULL
)

INSERT INTO CLASS_REVIEW VALUES(1,BOARDNOSEQ_SQ.NEXTVAL, QA_GROUPNO_SQ.NEXTVAL, 1 ,0 , 1 ,'1번째 글입니다.', 5, '강선웅')
INSERT INTO CLASS_REVIEW VALUES(2,BOARDNOSEQ_SQ.NEXTVAL, QA_GROUPNO_SQ.NEXTVAL, 1 ,0 , 1 ,'2번째 글입니다.', 5, '강선웅')

SELECT * FROM CLASS_REVIEW

SELECT * FROM CLASS_REVIEW  WHERE ClASS_NUM = (SELECT CLASS_NUM FROM CLASS_INFO WHERE CLASS_NUM = 1) ORDER BY QA_GROUPNO DESC, QA_GROUPSQ 

UPDATE CLASS_REVIEW SET REVIEW_CONTENT = '안녕' WHERE BOARD_NO = 1;

SELECT * FROM CLASS_REVIEW WHERE BOARD_NO = 1

DELETE FROM CLASS_REVIEW WHERE BOARD_NO = 4

-------------------------- 대댓글
INSERT INTO CLASS_REVIEW VALUES(1,BOARD_NO_SQ.NEXTVAL,
										(SELECT QA_GROUPNO FROM CLASS_REVIEW WHERE BOARD_NO= 13),
									    (SELECT QA_GROUPSQ FROM CLASS_REVIEW WHERE BOARD_NO= 13)+1, 
									    (SELECT QA_TITLETAB FROM CLASS_REVIEW WHERE BOARD_NO= 13)+1,  
									    1, '이제제발좀', 5, '성공하자') 
									    
									
									   SELECT QA_GROUPNO FROM CLASS_REVIEW WHERE BOARD_NO= 1