DROP TABLE LIVE;

DROP SEQUENCE LIVE_SEQ;

CREATE SEQUENCE LIVE_SEQ;

CREATE TABLE LIVE(LIVE_NUM NUMBER PRIMARY KEY,
CLASS_NUM NUMBER REFERENCES CLASS_INFO(CLASS_NUM),
LIVE_TITLE VARCHAR2(100),
LIVE_AUTHOR VARCHAR2(100),
LIVE_TIME DATE);

SELECT * FROM LIVE;