DROP TABLE ROADMAP_SUBSCRIBE ;

CREATE TABLE ROADMAP_SUBSCRIBE (
USER_NUM NUMBER NOT NULL REFERENCES USER_INFO(USER_NUM) ON DELETE CASCADE,
ROADMAP_NUM NUMBER NOT NULL REFERENCES ROADMAP_INFO(ROADMAP_NUM) ON DELETE CASCADE
);

SELECT * FROM ROADMAP_SUBSCRIBE;

UPDATE ROADMAP_INFO SET ROADMAP_SUBSCRIBE = ROADMAP_SUBSCRIBE+1 WHERE ROADMAP_NUM =1;

SELECT COUNT(*) FROM ROADMAP_SUBSCRIBE WHERE USER_NUM=1 AND ROADMAP_NUM=100;

SELECT * FROM ROADMAP_SUBSCRIBE WHERE USER_NUM=1 AND ROADMAP_NUM=6;

DELETE FROM ROADMAP_SUBSCRIBE;
