
--==========================0812 테이블 생성

DROP TABLE ROADMAP;

DROP SEQUENCE ROADMAP_SQ;

CREATE SEQUENCE ROADMAP_SQ;

CREATE TABLE ROADMAP(
ROADMAP_NO NUMBER PRIMARY KEY, --NEW
ROADMAP_DATE DATE NOT NULL, --NEW
ROADMAP_WRITER VARCHAR2(1000) NOT NULL, --USER_INFO : USER_ID
ROADMAP_TITLE VARCHAR2(1000) NOT NULL, --NEW
ROADMAP_CONTENT VARCHAR2(4000) NOT NULL, --NEW
ROADMAP_LECTURE_NO VARCHAR2(100), --CALSS_INFO
ROADMAP_LECTURE_CONTENT VARCHAR2(4000),--NEW
ROADMAP_STUDENT NUMBER DEFAULT 0 NOT NULL, -- 이건 어떻게 하지.. 본문에서는 검색해서 가져올것임
ROADMAP_LIKE NUMBER DEFAULT 0 NOT NULL, --NEW
ROADMAP_SHARE NUMBER DEFAULT 0 NOT NULL, --NEW
ROADMAP_CATEGORY VARCHAR2(100) NOT NULL --NEW
);

SELECT * FROM ROADMAP;

INSERT INTO ROADMAP VALUES(ROADMAP_SQ.NEXTVAL, SYSDATE,'qwqw', 'TEST01', 'TESTTEST', '1','LECTURE_CONTEXT', 0,0,0,'IT프로그래밍' );


