
--CLASS_INFO 테이블 ROADMAP_INFO테이블 먼저 만들어야함~!!

DROP TABLE ROADMAP_CON;

CREATE TABLE ROADMAP_CON(
CLASS_NUM NUMBER NOT NULL REFERENCES CLASS_INFO(CLASS_NUM) ON DELETE CASCADE, 
ROADMAP_NUM NUMBER NOT NULL REFERENCES ROADMAP_INFO(ROADMAP_NUM) ON DELETE CASCADE,
ROADMAP_CUE NUMBER NOT NULL 
);

SELECT * FROM ROADMAP_CON;
SELECT * FROM ROADMAP_CON WHERE ROADMAP_NUM=4;

SELECT CLASS_NUM FROM ROADMAP_CON WHERE ROADMAP_NUM = 4 ORDER BY ROADMAP_CUE;

DELETE ROADMAP_CON WHERE ROADMAP_NUM = 25;


