DROP TABLE ROADMAP_SUBSCRIBE ;

CREATE TABLE ROADMAP_SUBSCRIBE (
USER_NUM NUMBER NOT NULL REFERENCES USER_INFO(USER_NUM) ON DELETE CASCADE,
ROADMAP_NUM NUMBER NOT NULL REFERENCES ROADMAP_INFO(ROADMAP_NUM) ON DELETE CASCADE
);

