DROP
	TABLE
		SUBSCRIBE;

CREATE
	TABLE
		SUBSCRIBE(USER_NUM NUMBER REFERENCES USER_INFO(USER_NUM),
		CLASS_NUM NUMBER REFERENCES CLASS_INFO(CLASS_NUM)
		);

SELECT * FROM SUBSCRIBE;

INSERT INTO SUBSCRIBE VALUES(1,2);
INSERT INTO SUBSCRIBE VALUES(2,1);

SELECT * FROM CLASS_INFO WHERE CLASS_NUM IN(SELECT CLASS_NUM FROM SUBSCRIBE WHERE USER_NUM = 2);
