DROP TABLE SUBSCRIBE;

CREATE TABLE SUBSCRIBE(
USER_NUM NUMBER REFERENCES USER_INFO(USER_NUM) ON DELETE CASCADE,
CLASS_NUM NUMBER REFERENCES CLASS_INFO(CLASS_NUM) ON DELETE CASCADE
);

SELECT * FROM SUBSCRIBE;

-- 결제 완료시 강의 구독 수
INSERT INTO SUBSCRIBE(USER_NUM) SELECT DISTINCT USER_NUM FROM SUBSCRIBE VALUES(61,3);
INSERT INTO SUBSCRIBE VALUES(2,1);
INSERT INTO SUBSCRIBE VALUES(3,1);
INSERT INTO SUBSCRIBE VALUES(4,1);
-- View 보여질 Sql
SELECT * FROM CLASS_INFO WHERE CLASS_NUM IN(SELECT CLASS_NUM FROM SUBSCRIBE WHERE USER_NUM = 61);

UPDATE CLASS_INFO SET SUB_COUNT = (SELECT CLASS_NUM FROM SUBSCRIBE)

SELECT CLASS_NUM  FROM SUBSCRIBE WHERE USER_NUM = #{user_num };

DELETE FROM SUBSCRIBE;

DELETE FROM SUBSCRIBE;

SELECT * FROM CLASS_INFO WHERE CLASS_NUM IN(SELECT CLASS_NUM FROM SUBSCRIBE WHERE USER_NUM = 2);
------==================
select *
from 
(select user_num from class_info where class_num = 2) a full outer join
(select user_num from basket where class_num = 2) b using(user_num);

select class_num from class_info where class_num=1000;
--SUBSCRIBE/BASKET TABLE을 사용해야한다
SELECT CLASS_NUM FROM SUBSCRIBE WHERE USER_NUM = 1;
SELECT CLASS_NUM FROM BASKET WHERE USER_NUM=1;

SELECT * FROM 
(SELECT CLASS_NUM FROM SUBSCRIBE WHERE USER_NUM = 1)a FULL OUTER JOIN
(SELECT CLASS_NUM FROM BASKET WHERE USER_NUM=1)b USING(CLASS_NUM);

