DROP TABLE USER_INFO;

DROP SEQUENCE USER_INFO_SQ;

CREATE SEQUENCE USER_INFO_SQ;
CREATE TABLE USER_INFO(
USER_NUM NUMBER PRIMARY KEY,
USER_ID VARCHAR2(100) NOT NULL,
USER_PW VARCHAR2(50) NOT NULL,
USER_NAME VARCHAR2(25) NOT NULL,
USER_NICKNAME VARCHAR2(50) NOT NULL,
USER_GRADE VARCHAR2(10) NOT NULL,
USER_INFO VARCHAR2(250) NOT NULL,
CONSTRAINT grade_chk CHECK (USER_GRADE IN ('USER','ADMIN','TUTOR')));

SELECT * FROM USER_INFO;

INSERT INTO USER_INFO VALUES(USER_INFO_SQ.NEXTVAL, 'user','1234','testName','testNick','USER','sunwoong1995@naver.com');


------------------------------------------ 강좌 데이터
DROP TABLE CLASS_DATA;

DROP SEQUENCE CLASS_DATA_SQ;

CREATE SEQUENCE CLASS_DATA_SQ;

CREATE TABLE CLASS_DATA(
CLASS_NUM NUMBER REFERENCES CLASS_INFO(CLASS_NUM) ON DELETE CASCADE NOT NULL,
DATA_SUBHEAD VARCHAR2(250) NOT NULL,
DATA_SQ NUMBER NOT NULL,
DATA_TITLE VARCHAR2(250) NOT NULL,
DATA_DATA CLOB NOT NULL
);

SELECT * FROM CLASS_DATA;

INSERT INTO CLASS_DATA VALUES(CLASS_DATA_SQ.NEXTVAL, '소제목', 1, '과정제목', '과정영상')

------------------------------------------ 강좌 정보
DROP TABLE CLASS_INFO;

DROP SEQUENCE CLASS_INFO_SQ;

CREATE SEQUENCE CLASS_INFO_SQ;

CREATE TABLE CLASS_INFO(
CLASS_NUM NUMBER PRIMARY KEY NOT NULL,
CLASS_TITLE VARCHAR2(250) NOT NULL,
CLASS_AUTHOR VARCHAR2(50) NOT NULL,
CLASS_INTRO VARCHAR2(4000),
CLASS_RATING NUMBER  DEFAULT 0,
CLASS_PRICE NUMBER  DEFAULT 0,
CLASS_SUBCOUNT NUMBER DEFAULT 0,
CLASS_STUDENTLEVEL VARCHAR2(200) NOT NULL,
CLASS_CATEGORY VARCHAR2(100) 
);

SELECT * FROM CLASS_INFO;

INSERT INTO CLASS_INFO VALUES(CLASS_INFO_SQ.NEXTVAL,'제목', '강사명','강좌소개',0,0,0,'상급자','카테고리')


