DROP TABLE USER_INFO;

DROP SEQUENCE USER_INFO_SQ;

CREATE SEQUENCE USER_INFO_SQ;

CREATE TABLE USER_INFO(
USER_NUM NUMBER PRIMARY KEY,
USER_ID VARCHAR2(100) NOT NULL,
USER_PW VARCHAR2(50) NOT NULL,
USER_NAME VARCHAR2(25) NOT NULL,
USER_NICKNAME VARCHAR2(50) NOT NULL,
USER_GRADE VARCHAR2(10) NOT NULL,
CONSTRAINT grade_chk CHECK (USER_GRADE IN ('USER','ADMIN','TUTOR')));

SELECT * FROM USER_INFO;

INSERT INTO USER_INFO VALUES(USER_INFO_SQ.NEXTVAL, 'user','1234','testName','testNick','USER');


