------------------------------------------ 강좌 정보
DROP TABLE CLASS_INFO;

DROP SEQUENCE CLASS_INFO_SQ;

CREATE SEQUENCE CLASS_INFO_SQ;

CREATE TABLE CLASS_INFO(
CLASS_NUM NUMBER PRIMARY KEY NOT NULL,
USER_NUM NUMBER REFERENCES USER_INFO(USER_NUM),
CLASS_TITLE VARCHAR2(250) NOT NULL,
CLASS_AUTHOR VARCHAR2(50) NOT NULL,
CLASS_INTRO VARCHAR2(4000),
CLASS_LIVE VARCHAR2(1) DEFAULT 'N' NOT NULL CHECK(CLASS_LIVE IN('Y', 'N','y','n')),
CLASS_RATING NUMBER  DEFAULT 0,
CLASS_PRICE NUMBER  DEFAULT 0,
CLASS_SUBCOUNT NUMBER DEFAULT 0,
CLASS_STUDENTLEVEL VARCHAR2(200) NOT NULL,
CLASS_CATEGORY VARCHAR2(100) 
);

SELECT * FROM CLASS_INFO;

INSERT INTO CLASS_INFO VALUES(CLASS_INFO_SQ.NEXTVAL, 2,'제목', '강사명','강좌소개','Y',0,0,0,'상급자','카테고리');
INSERT INTO CLASS_INFO VALUES(CLASS_INFO_SQ.NEXTVAL, 2,'제목2', '강사명2','강좌소개2','Y',0,0,0,'상급자2','카테고리2');

------------------------------------------ 강좌 내용 - > DB추가
DROP TABLE CLASS_INTRODUCE;

CREATE TABLE CLASS_INTRODUCE(
CLASS_NUM NUMBER REFERENCES CLASS_INFO(CLASS_NUM) ON DELETE CASCADE NOT NULL,
CLASS_CONTENT CLOB NOT NULL
)

SELECT * FROM CLASS_INTRODUCE;

INSERT INTO CLASS_INTRODUCE VALUES(1, '가나다라마바사아자차카타파하');
------------------------------------------ 강좌 데이터
DROP TABLE CLASS_DATA;

DROP SEQUENCE DATA_CHAPTER_SQ;

CREATE SEQUENCE DATA_CHAPTER_SQ;

CREATE TABLE CLASS_DATA(
CLASS_NUM NUMBER REFERENCES CLASS_INFO(CLASS_NUM) ON DELETE CASCADE NOT NULL,
DATA_CHAPTER NUMBER NOT NULL,
DATA_SUBHEAD VARCHAR2(250) DEFAULT '소제목',
DATA_SQ NUMBER NOT NULL,
DATA_TITLE VARCHAR2(250) DEFAULT '타이틀',
DATA_YOUTUBE VARCHAR2(200) DEFAULT '유튜브 링크',
DATA_DATA CLOB DEFAULT '영상'
);

SELECT * FROM CLASS_DATA;

INSERT INTO CLASS_DATA VALUES(1,DATA_CHAPTER_SQ.NEXTVAL,'소제목', 1, '과정제목','유튜브 링크', '과정영상')

------------------------------------------ 요기부터는 수정중 이거나 작성 중 입니다.
------------------------------------------ 컬럼 1개 들어간다. 추가적으로  들어가게 하는 방법
UPDATE CLASS_DATA 	 
SET DATA_DATA = '99부탁한다.'
WHERE DATA_CHAPTER = 2 AND DATA_SQ IN (SELECT DATA_SQ
			 	       		   		   FROM (SELECT * FROM CLASS_DATA WHERE DATA_CHAPTER = 2)
        	  		  		   		   WHERE ROWNUM = 1);
												   
------------------------------------------ 구독자 수
DROP TABLE SUBSCRIBERS;
        	  		  		   		   
DROP SEQUENCE SUBSCRIBERS_SQ;        	  		

CREATE SEQUENCE SUBSCRIBERS_SQ;	  		

CREATE TABLE SUBSCRIBERS(
SEQ NUMBER NOT NULL,
ID VARCHAR2(100) NOT NULL , -- USER ID
CLASS_NUM NUMBER NOT NULL, -- 강좌 번호
CLASS_TITLE VARCHAR2(400) NOT NULL, -- 강좌 이름
PRIMARY KEY(CLASS_NUM,CLASS_TITLE),
CONSTRAINT CON_SUBSCRIBERSID FOREIGN KEY(ID) REFERENCES LOGIN(ID)
);








        	  		  		   		 