
--USER_INFO 테이블/ MAIN_STREAM 테이블 먼저 만들어야함!
DROP TABLE ROADMAP_INFO;
DROP SEQUENCE ROADMAP_SQ;

CREATE SEQUENCE ROADMAP_SQ;

CREATE TABLE ROADMAP_INFO(

ROADMAP_NUM NUMBER PRIMARY KEY, --NEW
USER_NUM NUMBER NOT NULL REFERENCES USER_INFO(USER_NUM) ON DELETE CASCADE, --USER_INFO : USER_NUM
ROADMAP_TITLE VARCHAR2(1000) NOT NULL, --NEW
ROADMAP_CONTENT CLOB, --NEW
ROADMAP_SUBSCRIBE NUMBER DEFAULT 0 NOT NULL, --NEW 
ROADMAP_LIKE NUMBER DEFAULT 0 NOT NULL, --NEW
ROADMAP_SHARE NUMBER DEFAULT 0 NOT NULL, --NEW
MAIN_NUM NUMBER NOT NULL REFERENCES MAIN_STREAM(MAIN_NUM) ON DELETE CASCADE --MAIN STREAM :MAIN_NUM
);


SELECT * FROM ROADMAP_INFO;

select ROADMAP_SQ.nextval from dual;
